In [51]:
import numpy as np
import pandas as pd

df = pd.read_csv("./data.csv")
df.head()

df.isna().sum()

# remove the unwanted columns
df.drop(["id", "Unnamed: 32"], axis=1, inplace=True)
df.shape

(569, 31)

In [52]:
# Encoding this (Y)column df["diagnosis"] to numerical format
y = df["diagnosis"]
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_pred = le.fit_transform(y)
y = pd.DataFrame(y_pred, columns=["diagnosis"])
y

     diagnosis
0            1
1            1
2            1
3            1
4            1
..         ...
564          1
565          1
566          1
567          1
568          0

[569 rows x 1 columns]

In [53]:
x = df.iloc[:, 1:31]
x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [54]:
# 4. Split into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

print(len(X_train))
print(len(y_test))
print(len(X_train))
print(len(y_test))
y_test

455
114
455
114

     diagnosis
204          0
70           1
131          1
431          0
540          0
..         ...
486          0
75           1
249          0
238          0
265          1

[114 rows x 1 columns]

In [64]:
# 5. Create KNN object
from sklearn.neighbors import KNeighborsClassifier

# k's value between 1-16 for better accuracy
knn = KNeighborsClassifier(n_neighbors=11)


# 6. Train the model
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
y_pred = pd.DataFrame(y_pred)
y_pred

C:\Users\KARAN\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

     0
0    0
1    1
2    1
3    0
4    0
..  ..
109  0
110  1
111  0
112  0
113  1

[114 rows x 1 columns]

In [65]:

# 8. Accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

# currently k = 11 gives the best accuracy among others
print("Accuracy:", accuracy)

Accuracy: 0.9824561403508771