In [ ]:
#                     Ordinal Encoder
# OrdinalEncoder converts ordered categories into numbers.
# It preserves the natural order

In [ ]:
import pandas  as pd
import numpy as np

df = pd.read_csv("../encoding_practice.csv")

#  Satisfaction Example

# Select the column
satisfaction = df[["Satisfaction"]]
satisfaction

   Satisfaction
0          Poor
1          Good
2     Excellent
3       Average
4          Good
5     Excellent
6          Poor
7          Good
8       Average
9     Excellent
10         Good
11         Poor

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# ordinalEncoder object             0        1        2          3
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good", "Excellent"]])
satisfaction_encoded = oe.fit_transform(satisfaction)
satisfaction_encoded

array([[0.],
       [2.],
       [3.],
       [1.],
       [2.],
       [3.],
       [0.],
       [2.],
       [1.],
       [3.],
       [2.],
       [0.]])

In [7]:
df["Encoded_satisfaction"] = satisfaction_encoded
df

,Student_ID,Name,Gender,City,Education,Satisfaction,Performance,Experience_Level,Age,Study_Hours,Marks,Encoded_satisfaction
0,101,Aarav,Male,Ahmedabad,BCA,Poor,Low,Beginner,21,2,42,0.0
1,102,Diya,Female,Mumbai,MCA,Good,Medium,Intermediate,24,5,68,2.0
2,103,Rohan,Male,Ahmedabad,BCA,Excellent,High,Beginner,22,3,51,3.0
3,104,Meera,Female,Surat,MBA,Average,Medium,Advanced,27,6,79,1.0
4,105,Kabir,Male,Delhi,MCA,Good,High,Intermediate,25,4,64,2.0
5,106,Anaya,Female,Mumbai,BCA,Excellent,High,Advanced,23,7,88,3.0
6,107,Vivaan,Male,Pune,MCA,Poor,Low,Beginner,21,1,35,0.0
7,108,Isha,Female,Ahmedabad,MBA,Good,Medium,Intermediate,26,5,72,2.0
8,109,Arjun,Male,Surat,BCA,Average,Medium,Intermediate,24,4,61,1.0
9,110,Sara,Female,Delhi,MCA,Excellent,High,Advanced,28,8,91,3.0
10,111,Dev,Male,Pune,MBA,Good,Low,Beginner,22,2,45,2.0
11,112,Kiara,Female,Mumbai,BCA,Poor,Medium,Advanced,25,6,81,0.0